processor:
  native:
    size:
      width: 256
      height: 256

output:
  targets:
    - name: prediction
      format: png
      mode: RGBA
      style: cover # cover | contain
      size:
        width: 256
        height: 256

    - name: input
      format: png
      mode: RGBA
      style: cover # cover | contain
      size:
        width: 64
        height: 64
      effects:
        - type: grayscale
          chance: 0.02
        - type: reduce_colors
          chance: 0.4
          colors:
            - count: 32
              chance: 0.25
            - count: 64
              chance: 0.25
            - count: 128
              chance: 0.25
            - count: 256
              chance: 0.25
        - type: reduce_alpha
          chance: 0.25


content:
  grid:
    size:
      max:
        width: 4
        height: 4
      min:
        width: 1
        height: 1
  types:
    - type: sprite
      chance: 0.8
      effects:
        - type: rotate
          chance: 0.15
          angle:
            min: -180
            max: 180
        - type: outline
          chance: 0.15

    - type: shape
      chance: 0.05
      shapes:
        - type: triangle
          chance: 0.25
        - type: hexagon
          chance: 0.25
        - type: oval
          chance: 0.25
        - type: line
          chance: 0.25

    - type: text
      chance: 0.15
      characters: 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz01234567890"!@#$%^&*()_-+={}[]:;<>,.?/~'

background:
  types:
    - type: solid
    chance: 0.5
    effects:
      - type: translucency
        chance: 0.1
        alpha:
          min: 0.1
          max: 0.9
#      - type: gradient
#        chance 0.1


